name: Release
on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: "Name of release, e.g. v1, v2 etc"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name autograding-release-bot
          git config user.email autograding-release-bot+education@github.com

      - name: Create release branch
        run: |
          git fetch origin
          git checkout -b release/${{ inputs.releaseName }} origin/main

      - name: Run build and commit to release/${{ inputs.releaseName }}
        run: |
          npm install --silent
          npm run build
          git add dist/
          git commit -m "Release ${{ inputs.releaseName }}" || echo "Nothing to commit"
          git push -f origin release/${{ inputs.releaseName }}
      - name: Tag and push v1
        run: |
          git tag -f ${{ inputs.releaseName }}
          git push origin ${{ inputs.releaseName }} --force
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.releaseName }}
          allowUpdates: true
